version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rssApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1d2faemxwhtr3"
s3_prefix = "rssApp"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

